FROM python:3.6

ADD . /home/dsqueue/ds_queue
RUN cd /home/dsqueue/ds_queue/cert && ./generateNewProdCert.sh
RUN pip install ds-common

RUN groupadd -r dsqueue && useradd -r -s /bin/false -g dsqueue dsqueue
RUN chown -R dsqueue:dsqueue /home/dsqueue

USER dsqueue

CMD bash -c '/home/dsqueue/ds_queue/q_admin.sh start "$TIMEOUT_QUEUE_AND_POLL" "$ALLOWED_IPS" "$LOG_LEVEL"'